no-resolv
no-hosts
server=8.8.8.8

# Balanceamento Round Robin: 1 Domínio = 3 IPs
address=/www.meutrabalho.com.br/172.28.1.1
address=/www.meutrabalho.com.br/172.28.1.2
address=/www.meutrabalho.com.br/172.28.1.3

# Rede Interna
address=/db.nemesis.local/172.28.0.20
